package og.acm.ecg;
/*
 * ecgApplication.java
 *
 * See EcgLicense.txt for License terms.
 */

/**
 *
 * @author Mauricio Villarroel (m.villarroel@acm.og)
 */

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class EcgApplication extends javax.swing.JFrame {
    /* Main GUI-Window Objects*/
    private EcgPlotWindow plotWin;
    private EcgParamWindow paramWin;
    private EcgLogWindow logWin;

    /**
     * Creates new form ecgApplication
     */
    public EcgApplication() {
        initComponents();
        initClasses();
        initWindow();
    }

    /**
     * Main entry for the application
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            throw new RuntimeException(e);
        }

        EcgApplication app = new EcgApplication();
        app.setVisible(true);
        app.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
    }

    /*
     * Init Child Classes
     */
    private void initClasses() {
        /* Main Calculation Objects */
        final EcgParam paramOb = new EcgParam();

        this.logWin = new EcgLogWindow();
        this.paramWin = new EcgParamWindow(paramOb, logWin);
        this.plotWin = new EcgPlotWindow(paramOb, logWin);
    }

    private void initWindow() {
        this.setSize(880, 510);
        this.setResizable(false);
        this.setLayout(new BorderLayout());

        JPanel toolPanel = new JPanel();
        toolPanel.setLayout(new FlowLayout());

        JButton settingBtn = new JButton("Parameters");
        settingBtn.addActionListener((ActionEvent e) -> paramWin.setVisible(true));
        toolPanel.add(settingBtn);

        JButton logBtn = new JButton("Show log");
        logBtn.addActionListener((ActionEvent e) -> logWin.setVisible(true));
        toolPanel.add(logBtn);

        JButton aboutBtn = new JButton("About");
        aboutBtn.addActionListener((ActionEvent e) -> {
            EcgAboutWindow aboutDialog = new EcgAboutWindow(this, true);
            aboutDialog.setVisible(true);
        });

        add(toolPanel, BorderLayout.SOUTH);
        add(plotWin, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {
        setTitle("Java ECG Generator");
        pack();
    }
}
